name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Build the Docker image
        run: docker-compose build    
      
#       - 
#         name: tag postgres
#         run: docker tag postgres 9326564676/postgres:11
      
      - 
        name: tag python app
        run: docker tag pythonapp 9326564676/pythonapp
      
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#       -
#         name: push postgres
#         run: docker push 9326564676/postgres:11
      -
        name: push pythonapp
        run: docker push 9326564676/pythonapp
